import { BrowserWindow } from 'electron'
import { join } from 'path'
import { homedir } from 'os'
import {
  readFileSync, writeFileSync, existsSync,
  mkdirSync, unlinkSync, watchFile, unwatchFile,
} from 'fs'
import type { StatuslineData } from '../shared/ipc-types'

const DEVDOCK_DIR = join(homedir(), '.devdock')
const STATUS_DIR = join(DEVDOCK_DIR, 'status')
const SCRIPT_PATH = join(DEVDOCK_DIR, 'statusline.sh')
const CLAUDE_SETTINGS_PATH = join(homedir(), '.claude', 'settings.json')

class StatuslineWatcher {
  private mainWindow: BrowserWindow | null = null
  private watchedFiles = new Map<string, string>() // sessionId -> filePath

  setMainWindow(win: BrowserWindow) {
    this.mainWindow = win
  }

  /** Deploy statusline script and inject into Claude settings */
  setup() {
    this.deployScript()
    this.injectSettings()
  }

  /** Start watching a session's status file */
  watchSession(sessionId: string) {
    if (this.watchedFiles.has(sessionId)) return

    const filePath = join(STATUS_DIR, `${sessionId}.json`)
    this.watchedFiles.set(sessionId, filePath)

    watchFile(filePath, { interval: 1000 }, () => {
      this.readAndEmit(sessionId, filePath)
    })
  }

  /** Stop watching and clean up temp file */
  unwatchSession(sessionId: string) {
    const filePath = this.watchedFiles.get(sessionId)
    if (!filePath) return

    unwatchFile(filePath)
    this.watchedFiles.delete(sessionId)
    try { unlinkSync(filePath) } catch { /* file may not exist */ }
  }

  /** Stop all watchers */
  unwatchAll() {
    for (const [sessionId] of this.watchedFiles) {
      this.unwatchSession(sessionId)
    }
  }

  private readAndEmit(sessionId: string, filePath: string) {
    try {
      const raw = readFileSync(filePath, 'utf-8')
      if (!raw.trim()) return
      const json = JSON.parse(raw)

      const data: StatuslineData = {
        sessionId,
        model: json.model?.display_name || json.model?.id || undefined,
        modelId: json.model?.id || undefined,
        contextUsedPercent: json.context_window?.used_percentage ?? undefined,
        contextRemainingPercent: json.context_window?.remaining_percentage ?? undefined,
        contextWindowSize: json.context_window?.context_window_size ?? undefined,
        inputTokens: json.context_window?.current_usage?.input_tokens ?? undefined,
        outputTokens: json.context_window?.current_usage?.output_tokens ?? undefined,
        cacheCreationTokens: json.context_window?.current_usage?.cache_creation_input_tokens ?? undefined,
        cacheReadTokens: json.context_window?.current_usage?.cache_read_input_tokens ?? undefined,
        costUsd: json.cost?.total_cost_usd ?? undefined,
      }

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.webContents.send('statusline-data', data)
      }
    } catch { /* file not ready or invalid JSON — ignore */ }
  }

  private deployScript() {
    mkdirSync(STATUS_DIR, { recursive: true })

    const script = `#!/bin/bash
# DevDock statusline bridge — captures Claude Code session data
# Auto-generated by DevDock. Do not edit manually.
SID="\${DEVDOCK_SESSION_ID}"
SDIR="${STATUS_DIR}"
if [ -n "$SID" ]; then
  mkdir -p "$SDIR"
  cat > "$SDIR/\${SID}.tmp"
  mv "$SDIR/\${SID}.tmp" "$SDIR/\${SID}.json"
else
  cat > /dev/null
fi
echo "DevDock"
`
    writeFileSync(SCRIPT_PATH, script, { mode: 0o755 })
  }

  private injectSettings() {
    try {
      mkdirSync(join(homedir(), '.claude'), { recursive: true })

      let settings: Record<string, any> = {}
      if (existsSync(CLAUDE_SETTINGS_PATH)) {
        settings = JSON.parse(readFileSync(CLAUDE_SETTINGS_PATH, 'utf-8'))
      }

      // Only inject if no statusline exists or if it's our script
      const existing = settings.statusLine?.command
      if (existing && !existing.includes('.devdock/statusline')) {
        // User has their own statusline — don't overwrite
        return
      }

      if (existing === SCRIPT_PATH) {
        // Already configured
        return
      }

      settings.statusLine = {
        type: 'command',
        command: SCRIPT_PATH,
      }

      writeFileSync(CLAUDE_SETTINGS_PATH, JSON.stringify(settings, null, 2))
    } catch { /* settings file issues — non-fatal */ }
  }
}

export const statuslineWatcher = new StatuslineWatcher()
